version: '3'
services:
  dns:
    image: mdpos
    network_mode: host
    command: ./mdpos 1
  node_0:
    image: mdpos
    network_mode: host
    ports:
      - 8000:8000
    command: ./mdpos 0 8000 9000 0
    hostname: node_0
  node_1:
    image: mdpos
    network_mode: host
    ports:
      - 8001:8000
    command: ./mdpos 0 8001 9001 1
    hostname: node_1
  node_2:
    image: mdpos
    network_mode: host
    ports:
      - 8002:8000
    command: ./mdpos 0 8002 9002 2
    hostname: node_2
  node_3:
    image: mdpos
    network_mode: host
    ports:
      - 8003:8000
    command: ./mdpos 0 8003 9003 3
    hostname: node_3
  node_4:
    image: mdpos
    network_mode: host
    ports:
      - 8004:8000
    command: ./mdpos 0 8004 9004 4
    hostname: node_4
